### ISSUE TITLE
admpanel/coachings

### ISSUE THREAD

**Issue by Type-IIx** [AhmedJB/apouletude#3]
Under the **Clickwrap agreement & waiver** column hardcoded text is being used that is not coming from the admpanel/settings Clickwrap agreements & waivers.

This issue **likely extends** to all other Formdata beyond admpanel/coachings – including /writings & /consultancy.

**Comment by Type-IIx** [comment]
This issue **does in fact** extend to _all_ sections (coaching, consultancy, & writing/authors).

Please **remove** the "Clickwrap Agreement & Waiver" column altogether from _all_ sections.

**Comment by AhmedJB** [comment]
done
