### ISSUE TITLE
Articles:TinyMCE editor style does not patch generated Article style

### ISSUE THREAD

**Issue by Type-IIx** [AhmedJB/apouletude#6]
When creating a new, or editing, an article using the TinyMCE interface, `<ul>, <ol>, <li>` items are displayed correctly in a WYSIWYG manner. However, after saving the article, these elements are not visible.

**Comment by Type-IIx** [comment]
**Note**: I kind of _hate_ TinyMCE, so consider replacing it outright, with something that works and that doesn't require email verification of domain ownership (especially considering smtp is blocked).

**Comment by AhmedJB** [comment]
Changed TinyMCE
